# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.



development:
  secret_key_base: f2fc3b28acd8b26933cae119ae58333d353126694ba90e4a401872dea8f1ad22c3534405af6bd499c3a22112cc0f21389e94ed8e06832da432ced9488abfc856
  twitter_api_public: <%= ENV["RPGUILD_TWITTER_PUBLICID"] %> 
  twitter_api_secret: <%= ENV["RPGUILD_TWITTER_SECRETID"] %> 
  facebook_public_id: <%= ENV["RPGUILD_FACEBOOK_PUBLICID"] %> 
  facebook_secret_id: <%= ENV["RPGUILD_FACEBOOK_SECRETID"] %> 
  github_client_public: <%= ENV["RPGUILD_GITHUB_PUBLICID"] %> 
  github_client_secret: <%= ENV["RPGUILD_GITHUB_SECRETID"] %> 

test:
  secret_key_base: 68e9e769a000697c1191aedaf8837067cdb13039f19bd14e552360706d1edf4476f55dd6fd9a54310b2fc9f51fe6d9cc018b27cea5b2ae42008ef0a2a45ef61a
  


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


